### ISSUE TITLE
where  is build.sbt file ?

### ISSUE THREAD

**Issue by zhangshengshan** [jsuereth/scala-arm#70]
As in title , where to find the build.sbt file to compile this project ?

**Comment by eed3si9n** [comment]
Back in sbt 0.13, the build could be described either using `build.sbt` or `project/Build.scala`, and sbt 1 unifies them to `build.sbt` since it is more convenient (thanks to auto plugin's auto import).
See https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#Migrating+from+the+Build+trait on how `project/Build.scala` can be migrated.
